apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: selsel
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
        version: "5"
    spec:
      containers:
      - name: api
        image: tira/api:5.8
        imagePullPolicy: Always
        resources:
          requests:
            cpu:  50m
            ephemeral-storage: 2Gi
            memory: 512Mi
          limits:
            cpu: 1000m
            ephemeral-storage: 5Gi
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /runner
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /runner
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 5000