apiVersion: v1
kind: Service
metadata:  
  name: ${APP-NAME}
  namespace: selsel  
spec: 
  ports:  
  - protocol: TCP
    port: 4444    
    targetPort: 4444
  selector:
    app: ${APP-NAME}
  type: LoadBalancer
