apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    environment: uat1
    replicaset: rs0
    role: mongo
  name: datadir-mongodb-2
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-standart-retain
  volumeMode: Filesystem
  volumeName: datadir-mongodb-2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    environment: uat1
    replicaset: rs0
    role: mongo
  name: datadir-mongodb-1
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-standart-retain
  volumeMode: Filesystem
  volumeName: datadir-mongodb-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    environment: uat1
    replicaset: rs0
    role: mongo
  name: datadir-mongodb-0
  namespace: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-standart-retain
  volumeMode: Filesystem
  volumeName: datadir-mongodb-0
