apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: uat1
        replicaset: rs0
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:4.4.9
          command:            
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"                      
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: uat1-pv
              mountPath: /data/db
          
  volumeClaimTemplates:
  - metadata:
      name: uat1-pv      
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-standart-retain
      resources:
        requests:
          storage: 8Gi
